# Setup
title:               Jacob Moore
tagline:             'A human being'
description:         'I read, and I write, and I try to take care of myself.'
url:                 https://moorejm.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jacob Moore
  url:               https://moorejm.com
  email:             jacob@moorejm.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
